from pathlib import Path


PLAN_PATH = Path(r"C:\Projeto Leitor de cod de barras\docs\superpowers\plans\2026-03-23-v1-plan.md")


REPLACEMENTS = [
    ("# Barcode App V1 Implementation Plan", "# Plano de Implementação da V1 do App de Código de Barras"),
    ("> **For agentic workers:** REQUIRED SUB-SKILL: Use superpowers:subagent-driven-development (recommended) or superpowers:executing-plans to implement this plan task-by-task. Steps use checkbox (`- [ ]`) syntax for tracking.",
     "> **Para agentes de implementação:** SUB-SKILL OBRIGATÓRIO: Use `superpowers:subagent-driven-development` (recomendado) ou `superpowers:executing-plans` para executar este plano tarefa por tarefa. As etapas usam checklist com sintaxe (`- [ ]`) para acompanhamento."),
    ("**Goal:** Build the first production-oriented version of a multi-company barcode collection system with Android camera scanning, web manual entry, desktop administration, offline-first local persistence, and Supabase-backed auth/sync.",
     "**Objetivo:** Construir a primeira versão orientada à produção de um sistema multiempresa para coleta de códigos de barras, com leitura por câmera no Android, entrada manual na web, administração no desktop, persistência local offline-first e autenticação/sincronização com Supabase."),
    ("**Architecture:** The app uses Flutter with MVVM and Riverpod, Drift as the offline-first local relational store, and Supabase for auth, cloud storage, RLS, and secure admin operations. Platform behavior is intentionally split: Android owns camera scanning, Chrome owns manual collection/export, and Windows desktop owns administration and audit workflows.",
     "**Arquitetura:** O aplicativo usa Flutter com MVVM e Riverpod, Drift como armazenamento relacional local offline-first e Supabase para autenticação, persistência em nuvem, RLS e operações administrativas seguras. O comportamento por plataforma é intencionalmente separado: Android concentra a leitura por câmera, Chrome concentra a coleta manual e a exportação, e Windows Desktop concentra administração e auditoria."),
    ("**Tech Stack:** Flutter, Dart, Riverpod, Drift, sqlite3/wasm, mobile_scanner, supabase_flutter, excel, pdf, printing, Vercel, Supabase Edge Functions",
     "**Stack Tecnológica:** Flutter, Dart, Riverpod, Drift, sqlite3/wasm, mobile_scanner, supabase_flutter, excel, pdf, printing, Vercel, Supabase Edge Functions"),
    ("## Planned File Structure", "## Estrutura de Arquivos Planejada"),
    ("### Root and Tooling", "### Raiz e Ferramentas"),
    ("### App Shell", "### Estrutura Base do App"),
    ("### Shared Core", "### Núcleo Compartilhado"),
    ("### Features", "### Funcionalidades"),
    ("### Data Layer", "### Camada de Dados"),
    ("### Tests", "### Testes"),
    ("## Delivery Strategy", "## Estratégia de Entrega"),
    ("This project spans multiple subsystems, so execution should happen in vertical slices:", "Este projeto cobre vários subsistemas, então a execução deve acontecer em fatias verticais:"),
    ("1. Foundation and workspace bootstrap", "1. Fundação e bootstrap do workspace"),
    ("2. Offline data and sync primitives", "2. Dados offline e primitivas de sincronização"),
    ("3. Authentication and company access", "3. Autenticação e acesso por empresa"),
    ("4. Collections and readings", "4. Coletas e leituras"),
    ("5. Android scanner and web/manual flows", "5. Scanner Android e fluxos web/manuais"),
    ("6. Export, admin, audit, and release hardening", "6. Exportação, administração, auditoria e endurecimento para release"),
    ("Each slice must end in a working state before the next one begins.", "Cada fatia deve terminar em estado funcional antes do início da próxima."),
    ("**Files:**", "**Arquivos:**"),
    ("- Create:", "- Criar:"),
    ("- Modify:", "- Modificar:"),
    ("- Test:", "- Teste:"),
    ("### Task 1: Bootstrap the Flutter workspace", "### Tarefa 1: Fazer o bootstrap do workspace Flutter"),
    ("### Task 2: Establish app routing and startup bootstrap", "### Tarefa 2: Estruturar roteamento e inicialização do app"),
    ("### Task 3: Create the local Drift database foundation", "### Tarefa 3: Criar a base local do banco com Drift"),
    ("### Task 4: Add DAOs and sync queue primitives", "### Tarefa 4: Adicionar DAOs e primitivas da fila de sincronização"),
    ("### Task 5: Add Supabase bootstrap and authenticated session state", "### Tarefa 5: Adicionar bootstrap do Supabase e estado de sessão autenticada"),
    ("### Task 6: Implement login by matrícula using a technical Supabase identity", "### Tarefa 6: Implementar login por matrícula usando identidade técnica no Supabase"),
    ("### Task 7: Implement multi-company access and active company switching", "### Tarefa 7: Implementar acesso multiempresa e troca de empresa ativa"),
    ("### Task 8: Add the collection domain and collection list UI", "### Tarefa 8: Adicionar o domínio de coletas e a interface da lista de coletas"),
    ("### Task 9: Implement reading registration, duplicate warnings, and live list updates", "### Tarefa 9: Implementar registro de leituras, aviso de duplicidade e atualização em tempo real da lista"),
    ("### Task 10: Add the Android camera scanner flow", "### Tarefa 10: Adicionar o fluxo de scanner por câmera no Android"),
    ("### Task 11: Add manual code entry for Chrome and Windows", "### Tarefa 11: Adicionar entrada manual de código para Chrome e Windows"),
    ("### Task 12: Implement sync engine polling and retry behavior", "### Tarefa 12: Implementar o motor de sincronização com polling e retentativas"),
    ("### Task 13: Add export to XLSX and PDF", "### Tarefa 13: Adicionar exportação para XLSX e PDF"),
    ("### Task 14: Add admin user management and role assignment", "### Tarefa 14: Adicionar gestão administrativa de usuários e atribuição de papéis"),
    ("### Task 15: Add audit logging and permission-gated edit/delete actions", "### Tarefa 15: Adicionar logs de auditoria e ações de editar/excluir condicionadas por permissão"),
    ("### Task 16: Add PWA config, deployment config, and full verification", "### Tarefa 16: Adicionar configuração de PWA, configuração de deploy e verificação completa"),
    ("## Final Verification Checklist", "## Checklist Final de Verificação"),
    ("## Notes for Execution", "## Observações para Execução"),
    ("Run: ", "Executar: "),
    ("Expected: ", "Esperado: "),
    ("Step ", "Etapa "),
    ("Write the failing", "Escrever o teste falhando para"),
    ("Write the failing schema test", "Escrever o teste falhando do schema"),
    ("Write the failing DAO test", "Escrever o teste falhando do DAO"),
    ("Write the failing auth test", "Escrever o teste falhando de autenticação"),
    ("Write the failing login widget test", "Escrever o teste falhando do widget de login"),
    ("Write the failing company access test", "Escrever o teste falhando de acesso por empresa"),
    ("Write the failing collections page test", "Escrever o teste falhando da página de coletas"),
    ("Write the failing duplicate policy test", "Escrever o teste falhando da política de duplicidade"),
    ("Write the failing scanner widget test", "Escrever o teste falhando do widget do scanner"),
    ("Write the failing manual entry test", "Escrever o teste falhando de entrada manual"),
    ("Write the failing sync controller test", "Escrever o teste falhando do controlador de sincronização"),
    ("Write the failing export tests", "Escrever os testes falhando de exportação"),
    ("Write the failing admin permission test", "Escrever o teste falhando de permissão administrativa"),
    ("Write the failing audit test", "Escrever o teste falhando de auditoria"),
    ("Write the failing integration test skeleton", "Escrever o esqueleto do teste de integração falhando"),
    ("Create the Flutter project in the current workspace", "Criar o projeto Flutter no workspace atual"),
    ("Add the baseline dependencies", "Adicionar as dependências iniciais"),
    ("Run dependency resolution", "Executar a resolução de dependências"),
    ("Run the smoke test to verify it fails", "Executar o teste de smoke para confirmar que ele falha"),
    ("Add the minimum app shell", "Adicionar a estrutura mínima do app"),
    ("Run the smoke test again", "Executar o teste de smoke novamente"),
    ("Establish app routing and startup bootstrap", "Estruturar roteamento e inicialização do app"),
    ("Write the failing routing test", "Escrever o teste falhando de roteamento"),
    ("Run the routing test", "Executar o teste de roteamento"),
    ("Add bootstrap and router files", "Adicionar os arquivos de bootstrap e roteador"),
    ("Wire router and theme into the app", "Conectar roteador e tema ao app"),
    ("Run the routing test again", "Executar novamente o teste de roteamento"),
    ("Create the Drift tables", "Criar as tabelas do Drift"),
    ("Create the database class", "Criar a classe do banco"),
    ("Generate Drift code", "Gerar o código do Drift"),
    ("Wire the tables into the database annotation", "Conectar as tabelas à anotação do banco"),
    ("Run the schema test again", "Executar novamente o teste do schema"),
    ("Implement the readings DAO", "Implementar o DAO de leituras"),
    ("Implement `sync_queue_dao.dart`", "Implementar `sync_queue_dao.dart`"),
    ("Replace placeholder assertions with a real DAO test", "Substituir as asserções provisórias por um teste real do DAO"),
    ("Run the DAO test again", "Executar novamente o teste do DAO"),
    ("Model the current session", "Modelar a sessão atual"),
    ("Add the Supabase provider", "Adicionar o provider do Supabase"),
    ("Implement the auth controller", "Implementar o controlador de autenticação"),
    ("Replace the placeholder auth test", "Substituir o teste provisório de autenticação"),
    ("Run the auth test again", "Executar novamente o teste de autenticação"),
    ("Model the login request", "Modelar a requisição de login"),
    ("Build the login page", "Construir a página de login"),
    ("Implement repository login", "Implementar o login no repositório"),
    ("Route unauthenticated users to `LoginPage`", "Direcionar usuários não autenticados para `LoginPage`"),
    ("Run the login widget test again", "Executar novamente o teste do widget de login"),
    ("Model company access", "Modelar o acesso por empresa"),
    ("Implement the active company controller", "Implementar o controlador da empresa ativa"),
    ("Add the company switcher UI", "Adicionar a interface de troca de empresa"),
    ("Replace the placeholder assertion", "Substituir a asserção provisória"),
    ("Run the company access test again", "Executar novamente o teste de acesso por empresa"),
    ("Add collection models and repository", "Adicionar modelos e repositório de coletas"),
    ("Build the collections page", "Construir a página de coletas"),
    ("Route authenticated users to `/collections`", "Direcionar usuários autenticados para `/collections`"),
    ("Run the collections widget test again", "Executar novamente o teste do widget de coletas"),
    ("Add a unit test for creating a collection", "Adicionar um teste unitário para criação de coleta"),
    ("Model the reading input", "Modelar a entrada de leitura"),
    ("Implement the controller logic", "Implementar a lógica do controlador"),
    ("Add the readings page", "Adicionar a página de leituras"),
    ("Add the widget test for the total counter", "Adicionar o teste de widget para o contador total"),
    ("Run the reading tests", "Executar os testes de leitura"),
    ("Model platform capabilities", "Modelar as capacidades por plataforma"),
    ("Implement the Android scanner view", "Implementar a view do scanner Android"),
    ("Add a fallback path for unsupported platforms", "Adicionar um caminho alternativo para plataformas sem suporte"),
    ("Run the scanner widget test again", "Executar novamente o teste do widget do scanner"),
    ("Run an Android smoke check", "Executar uma verificação rápida no Android"),
    ("Implement the manual entry form", "Implementar o formulário de entrada manual"),
    ("Add the form to unsupported scanner platforms", "Adicionar o formulário às plataformas sem scanner"),
    ("Run the manual entry widget test again", "Executar novamente o teste do widget de entrada manual"),
    ("Smoke test on Chrome and Windows", "Fazer smoke test no Chrome e no Windows"),
    ("Implement the sync controller", "Implementar o controlador de sincronização"),
    ("Add the sync banner", "Adicionar o banner de sincronização"),
    ("Replace the placeholder test with a fake-backed repository test", "Substituir o teste provisório por um teste com repositório fake"),
    ("Run the sync controller test again", "Executar novamente o teste do controlador de sincronização"),
    ("Add the banner to collection and reading pages", "Adicionar o banner às páginas de coletas e leituras"),
    ("Run the export tests", "Executar os testes de exportação"),
    ("Implement XLSX export", "Implementar a exportação XLSX"),
    ("Implement PDF export", "Implementar a exportação PDF"),
    ("Add export buttons to the collection UI", "Adicionar botões de exportação à interface da coleta"),
    ("Run the export tests again", "Executar novamente os testes de exportação"),
    ("Model the admin create request", "Modelar a requisição administrativa de criação de usuário"),
    ("Implement the admin repository against an Edge Function", "Implementar o repositório administrativo usando uma Edge Function"),
    ("Build the admin users page", "Construir a página administrativa de usuários"),
    ("Add the admin widget test", "Adicionar o teste de widget administrativo"),
    ("Run the admin tests again", "Executar novamente os testes administrativos"),
    ("Implement audit repository methods", "Implementar os métodos do repositório de auditoria"),
    ("Gate edit and delete actions by role", "Controlar ações de editar e excluir por papel"),
    ("Add the audit page", "Adicionar a página de auditoria"),
    ("Add a widget test for action visibility", "Adicionar um teste de widget para visibilidade das ações"),
    ("Run both audit tests", "Executar os dois testes de auditoria"),
    ("Configure the PWA manifest", "Configurar o manifesto do PWA"),
    ("Add Vercel config and environment template", "Adicionar configuração da Vercel e template de ambiente"),
    ("Replace the integration placeholder", "Substituir o placeholder da integração"),
    ("Run the full test suite", "Executar a suíte completa de testes"),
    ("Run platform smoke checks", "Executar verificações rápidas por plataforma"),
    ("Use `@superpowers/test-driven-development` during implementation of each task.", "Use `@superpowers/test-driven-development` durante a implementação de cada tarefa."),
    ("Use `@superpowers/verification-before-completion` before claiming a task is done.", "Use `@superpowers/verification-before-completion` antes de afirmar que uma tarefa foi concluída."),
    ("Do not implement PDF barcode extraction in this plan.", "Não implemente extração de códigos de barras em PDF neste plano."),
    ("Do not add camera scanning to Chrome or Windows in this plan.", "Não adicione leitura por câmera no Chrome ou no Windows neste plano."),
    ("Keep the technical Supabase identity hidden from UI copy and operator workflows.", "Mantenha a identidade técnica do Supabase oculta da interface e dos fluxos operacionais."),
    ("PASS.", "SUCESSO."),
    ("FAIL.", "FALHA."),
]


def main() -> None:
    text = PLAN_PATH.read_text(encoding="utf-8")

    for old, new in REPLACEMENTS:
        text = text.replace(old, new)

    text = text.replace("**Step ", "**Etapa ")
    text = text.replace("Commit**", "Commit**")

    PLAN_PATH.write_text(text, encoding="utf-8")
    print(PLAN_PATH)


if __name__ == "__main__":
    main()
